config/routes.rb
Fintech::Application.routes.draw do

  match 'courses/excel' => 'courses#excel'
  match '/home' => 'static_pages#home'
  match '/equity_track' => 'static_pages#equity_track'
  match '/tracks' => 'static_pages#tracks'

  resources :courses
  root :to => 'static_pages#home'

end

app/models/course.rb
class Course < ActiveRecord::Base
  attr_accessible :title, :steps_attributes
  has_many :steps
  accepts_nested_attributes_for :steps, allow_destroy: true
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :course
  attr_accessible :description, :answer, :course_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  # respond_to    :html, :json

  def index
    @courses = Course.all

    respond_to do |format|
      format.html
      format.json { render :json => @courses }
    end
  end

  def show
    @course = Course.find(params[:id])

    respond_to do |format|
      format.json { 
        render :json => @course.to_json(:include => :steps) 
      }
    end

  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(params[:course])
    if @course.save
      redirect_to @course, notice: "Successfully created Course."
    else
      render :new
    end
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    if @course.update_attributes(params[:course])
      redirect_to @course, notice: "Successfully updated course."
    else
      render :edit
    end
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to courses_url, notice: "Successfully destroyed course."
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
		render :layout => "home_layout"
	end

	def equity_track
		render :layout => "equity_track_layout"
	end

	def tracks
		render :layout => "tracks_layout"
	end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  respond_to    :html, :json

  def index
    @steps = Step.all
    respond_with(@steps)
  end

  def show
    # @course = Course.find(params[:course_id])
    # @step = @course.steps.build
    @step = get_step(params[:id]) 
    respond_with(@step)
  end
  
  def new
    # @step = Step.new(@course)
    # @course = Course.find(params[:course_id])
    # @step = @course.steps.build
  end

  def create
    # @step = Step.new(params[:course])
    # @course = Course.find(params[:course_id])
    # @step = @course.step.build(params[:step])
    # if @step.save
      # redirect_to(@step, :notice => 'Step added successfully!')
    # else
      # render :new
    # end
  end
  
  def edit
    # @step = get_course(params[:id]) 
  end
  
  def update
    # @step = get_course(params[:id]) 
    # if @step.update_attributes(params[:step])
      # redirect_to(@step, :notice => 'Step updated')
    # else
      # render :edit
    # end
  end

  def destroy
    # @step = get_step(params[:id])
    # if @step.destroy
      # redirect_to new_course_path
    # end
  end


  def get_step(step_id)
    Step.find(step_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
    <%= f.fields_for :steps do |builder| %>
       <%= render 'step_fields', f: builder %>
    <% end %>

  <%= link_to_add_fields "Add a step", f, :steps %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/_step_fields.html.erb
<fieldset>
  <%= f.label :description, "Description" %><br />
  <%= f.text_area :description %><br />
  <%= f.label :answer, "Answer" %><br />
  <%= f.number_field :answer %><br />
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, "Remove Step" %>
</fieldset>

app/views/courses/_submit_btn.html.erb
<!-- <input type="submit" name="submit" onClick="execute();"></input> -->

<a href="#myModal" role="button" class="btn" data-toggle="modal" id="answer_button" onClick="execute();">Submit</a>

<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Results</h3>
  </div>
  <div class="modal-body">
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>

app/views/courses/new.html.erb
<section class="span12">
  <section id="content-area" class="center">
  <h2>Add Step</h2>
  <div class="inputs">
    <%= render 'form' %>
  </div>
</section>

app/views/layouts/_footer.html.erb
<input type="submit" name="submit" onClick="execute();"></input>

<a href="#myModal" role="button" class="btn" data-toggle="modal" id="answer_button">Submit</a>

<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Results</h3>
  </div>
  <div class="modal-body">
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Try Again!</button>
  </div>
</div>

app/views/layouts/_header.html.erb
  <header id="main">
    <div class="row">
        <div class="navbar navbar-inverse">
          <div class="navbar-inner">
            <div class="container">

              <div class="nav-collapse collapse">
                <ul class="nav">
                  <li>
                    <a href="#" class="home_page">
                      Finacademy
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      Learn
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      About
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      Progress
                    </a>
                  </li>
                  <li class="progress">
                    <div class="bar" style="width: 45%;"></div>
                      <a href="#" data-toggle="tooltip" title="45% complete">
                      
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      Level
                    </a>
                  </li>

                  <li>
                    <a href="#">
                      Profile
                    </a>
                  </li>

                   <li>
                    <a href="#">
                      Points
                    </a>
                  </li>
                </ul>
              </div><!--/.nav-collapse -->
            </div>
          </div>
        </div>
    </div>

  </header> 

app/views/layouts/_reading.html.erb
<div id="reading_area"></div>

app/views/layouts/_sidebar.html.erb
<div id="editor"></div>

<div class="submit_btn">
  <%= render 'submit_btn' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <title>Finacademy</title>
  <meta http-equiv="X-UA-Compatible" content="IE=9">

</head>
<body>
  <div class="header">
    <%= render 'layouts/header' %>
  </div>
<div id="container" class="container-fluid">
  

  <div id="content">
    <div class="sidebar">
      <%= render 'layouts/sidebar' %>
    </div>

    <div class="reading">
      <%= render 'layouts/reading' %>
    </div>

    <div class="lesson">
        <%= yield %>
    </div>

  </div>



</body>
</html>

app/views/layouts/equity_track_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <title>FinanceAcademy</title>
  <meta http-equiv="X-UA-Compatible" content="IE=9">

  <!-- Load the Realtime libraries. -->
  <script type="text/javascript"
          src="https://apis.google.com/js/api.js"></script>

  <!-- Load the utility library. -->
  <!-- <%= javascript_include_tag "realtime-client-utils" %> -->

</head>
<body onLoad='startRealtime()'>
<div id="container" class="container-fluid">
  <div class="header">
    <%= render 'layouts/header' %>
  </div>

        <%= yield %>
    

</div>

</body>
</html>

app/views/layouts/home_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <title>FinanceAcademy</title>
  <meta http-equiv="X-UA-Compatible" content="IE=9">

  <!-- Load the Realtime libraries. -->
  <script type="text/javascript"
          src="https://apis.google.com/js/api.js"></script>

  <!-- Load the utility library. -->
  <!-- <%= javascript_include_tag "realtime-client-utils" %> -->

</head>
<body onLoad='startRealtime()'>


        <%= yield %>




</body>
</html>

app/views/layouts/tracks_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <title>FinanceAcademy</title>
  <meta http-equiv="X-UA-Compatible" content="IE=9">

  <!-- Load the Realtime libraries. -->
  <script type="text/javascript"
          src="https://apis.google.com/js/api.js"></script>

  <!-- Load the utility library. -->
  <!-- <%= javascript_include_tag "realtime-client-utils" %> -->

</head>
<body onLoad='startRealtime()'>
<div id="container" class="container-fluid">
  <div class="header">
    <%= render 'layouts/header' %>
  </div>

        <%= yield %>
    

</div>

</body>
</html>

app/views/static_pages/equity_track.html.erb
      <div style="padding-left:500px;">
        <h1 class="demo-logo">
          <small>The Equity Course Information:</small>
        </h1>

      <div class="row demo-samples">
        <div class="span4">
          <br/>
          <br/>
          <br/>
          <div class="todo mrm">
            
            <ul>

              <li>
                <div class="todo-icon fui-menu-24"></div>
                <div class="todo-content">
                  <h4 class="todo-name">
                    Income <strong>Statement</strong>
                  </h4>
                  Historical Info and Estimates
                </div>
              </li>

              <li>
                <div class="todo-icon fui-eye-24"></div>
                <div class="todo-content">
                  <h4 class="todo-name">
                    Balance <strong>Sheet</strong>
                  </h4>
                  Estimate run-rate ratios
                </div>
              </li>

              <li>
                <div class="todo-icon fui-time-24"></div>
                <div class="todo-content">
                  <h4 class="todo-name">
                    Cash <strong>Flow</strong>
                  </h4>
                  Calculate cash available
                </div>
              </li>
            </ul>
          </div>
        </div> <!-- /todo list -->
      </div>
            <div class="row demo-row">

        <div style="padding-left:35px;" class="span3">
          <a href="#" class="btn btn-large btn-block btn-primary">Continue</a>
        </div>

      </div> <!-- /row -->

app/views/static_pages/home.html.erb
	    
      <div class="container" id="home_page">
      
      <div class="demo-headline">

        <h1 class="demo-logo">
            
          <div class="logo"></div>
             <div>
      <%= image_tag "home-image.png" , :size=>"400x400", :class => "logo_large" %>
      </div>
          Fincademy
          <small>An interactive tutorial to learn Financial Modeling</small>
        </h1>
        	<br>
		<%= link_to "Sign up now!", tracks_path, class: "btn btn-large btn-primary" %>
	</div> <!-- /demo-headline -->

app/views/static_pages/tracks.html.erb
      <div class="row demo-tiles">
        <div class="span3">
          <div class="tile">
            <%= image_tag "illustrations/compass.png" %>
         
            <h3 class="tile-title">Basics of Finance</h3>
            <p>If you are completely new to Finance, this track is the place to start.</p>
            <a class="btn btn-primary btn-large btn-block" href="#">Go to Track</a>
          </div>
        </div>

        <div class="span3">
          <div class="tile">
            <%= image_tag "illustrations/infinity.png" %>

            <h3 class="tile-title">Equity</h3>
            <p>Learn how to build an equity financial model from start to finish.</p>
            <%= link_to "Go to Track", courses_excel_path, :class => "btn btn-primary btn-large btn-block" %>
            <!-- <a class="btn btn-primary btn-large btn-block" href="#">Go to Track</a> -->
          </div>
        </div>

        <div class="span3">
          <div class="tile">
            <%= image_tag "illustrations/colors.png" %>

            <h3 class="tile-title">Startup</h3>
            <p>Learn to build financial models for startups or venture capital </p>
            <a class="btn btn-primary btn-large btn-block" href="#">Go to Track</a>
          </div>
        </div>

        <div class="span3">
          <div class="tile">
            <%= image_tag "illustrations/book.png" %>

            <h3 class="tile-title">Alt. Investments</h3>
            <p>Build financial models for more differentiated investments</p>
            <a class="btn btn-primary btn-large btn-block" href="#">Go to Track</a>
          </div>
        </div>

      </div> <!-- /tiles -->